"""
Plots phonon band structure.
Needs .yaml file generated by Phonopy which contains eigenvalues for each |n,k>.
"""
import yaml
import numpy as np
import matplotlib.pyplot as plt

with open("band.yaml", 'r') as file:
    data = yaml.safe_load(file)

nbands = 5  # Number of bands from the bottom to plot.

ph = data['phonon']
y = [[ph[i]['band'][j]['frequency'] for i in range(len(ph))] for j in range(nbands)]
y = np.array(y)
y = np.vstack([y, np.zeros(len(y[0]))])


fig, (ax1,ax2) = plt.subplots(1, 2, sharey=True, gridspec_kw={'width_ratios': [2, 1]}, constrained_layout=True)

x = np.arange(0,404)
ax1.plot(x, y.T[:404], linewidth=0.5)
ax1.set_xticks([0,100,201,302,403])
ax1.set_xticklabels(['Γ','Y','M','A','Γ'])
ax1.tick_params(axis='y', which='both', left=False)
ax1.set_ylabel('Frequency')

x = np.arange(0,202)
ax2.plot(x, y.T[404:], linewidth=0.5)
ax2.set_xticks([0,100,201])
ax2.set_xticklabels(['L2','Γ','V2'])

plt.savefig('band_zoom.pdf')
